AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for configuring CloudWatch alarms in the EPS account.
  
Parameters:
  ConcurrencyThreshold:
    Type: Number
    Description: Threshold for the Lambda concurrency.
    Default: 300
    
  EnableAlerts:
    Type: String
    AllowedValues: [ 'true', 'false' ]
    Default: 'true'
    Description: Whether to enable or disable alarms and notifications.
  
Resources:
  EPSAccountConcurrencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmName: Account_Lambda_Concurrency
      AlarmDescription: "Monitors the concurrency of all traffic coming through the EPS account, and triggers when concurrency exceeds the threshold."
      Namespace: "AWS/Lambda"
      MetricName: "ConcurrentExecutions"
      Statistic: Maximum
      Period: 300 # seconds
      EvaluationPeriods: 1
      Threshold: !Ref ConcurrencyThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      ActionsEnabled: !Ref EnableAlerts
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
