AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EPSZone:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneConfig:
        Comment: "hosted zone for eps"
      Name: "eps.national.nhs.uk"

  nsDevHostedEPSZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: !Ref EPSZone
      Name: "dev.eps.national.nhs.uk"
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "ns-352.awsdns-44.com", 
          "ns-1093.awsdns-08.org", 
          "ns-728.awsdns-27.net", 
          "ns-1618.awsdns-10.co.uk",
        ]

  nsQAHostedEPSZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: !Ref EPSZone
      Name: "qa.eps.national.nhs.uk"
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "changeme.com", 
        ]

  nsIntHostedEPSZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: !Ref EPSZone
      Name: "int.eps.national.nhs.uk"
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "changeme.com", 
        ]

  nsRefHostedEPSZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: !Ref EPSZone
      Name: "ref.eps.national.nhs.uk"
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "changeme.com", 
        ]

  nsProdHostedEPSZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: !Ref EPSZone
      Name: "prod.eps.national.nhs.uk"
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "changeme.com", 
        ]
