AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  PSUNotifyAppKIDValue:
    Type: String
    Description: KID value for PSU Notify App (set per environment)
    Default: psu-notify-prod-1
Resources:
  PrescribingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPrivateKey"

  PrescribingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPublicKey"

  DispensingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPrivateKey"

  DispensingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPublicKey"

  PrescriptionsForPatientsProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenPrivateKey"

  PrescriptionsForPatientsProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenPublicKey"

  epsSigningCertChain:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Cert chain used for signing prescriptions. Used to validate prescriptions are valid
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-epsSigningCertChain"

  epsSigningCertChainManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !GetAtt epsSigningCertChain.Id

  ptlPrescriptionSigningPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPrivateKey"

  ptlPrescriptionSigningPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPublicKey"

  PSUNotifyCallbackAppName:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The Digital Onboarding Service application name used when calculating the signature for the notify callback (e.g. EPS PSU notify callback int)
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-Application-Name"

  PSUNotifyAppKID:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The KID used in the JWT header when sending notifications to NHS Notify (e.g. psu-notify-prod-1)
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: !Ref PSUNotifyAppKIDValue
      Name: !Sub "${AWS::StackName}-PSU-Notify-Application-KID"

  PSUNotifyCallbackApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The API key used when calculating the signature for the NHS notify callback
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-API-Key"

  PSUNotifyPrivateKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: RSA private key (PEM) for signing JWT to NHS Notify
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-PrivateKey"

  PSUNotifyAppIdSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The application ID for the DoS application to use when sending notifications to NHS Notify (e.g. bd492cde-b67e-487b-97fd-44b7414c8e95)
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-Application-ID"

  GetNotifySecretsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref PSUNotifyCallbackAppName
              - !Ref PSUNotifyAppKID
              - !Ref PSUNotifyCallbackApiKey
              - !Ref PSUNotifyPrivateKeySecret
              - !Ref PSUNotifyAppIdSecret

  #endregion

Outputs:
  PrescribingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPrivateKey"]]

  PrescribingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPublicKey"]]

  DispensingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPrivateKey"]]

  DispensingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPublicKey"]]

  FhirPrescribingProxygenPrivateKey:
    Description: FhirPrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPrivateKey"]]

  FhirPrescribingProxygenPublicKey:
    Description: FhirPrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPublicKey"]]

  FhirDispensingProxygenPrivateKey:
    Description: FhirDispensingProxygenPrivateKey
    Value: !GetAtt DispensingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPrivateKey"]]

  FhirDispensingProxygenPublicKey:
    Description: FhirDispensingProxygenPublicKey
    Value: !GetAtt DispensingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPublicKey"]]

  PrescriptionsForPatientsProxygenPrivateKey:
    Description: PrescriptionsForPatientsProxygenPrivateKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPrivateKey"]]

  PrescriptionsForPatientsProxygenPublicKey:
    Description: PrescriptionsForPatientsProxygenPublicKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPublicKey"]]

  epsSigningCertChain:
    Description: epsSigningCertChain
    Value: !GetAtt epsSigningCertChain.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChain"]]

  epsSigningCertChainManagedPolicy:
    Description: epsSigningCertChainManagedPolicy
    Value: !GetAtt epsSigningCertChainManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChainManagedPolicy"]]

  ptlPrescriptionSigningPublicKey:
    Description: ptlPrescriptionSigningPublicKey
    Value: !GetAtt ptlPrescriptionSigningPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPublicKey"]]

  ptlPrescriptionSigningPrivateKey:
    Description: ptlPrescriptionSigningPrivateKey
    Value: !GetAtt ptlPrescriptionSigningPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPrivateKey"]]

  #region Notify Secrets Outputs
  PSUNotifyCallbackAppName:
    Description: NHS Notify DoS application name (e.g. EPS PSU notify callback int) secret ARN
    Value: !GetAtt PSUNotifyCallbackAppName.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyCallbackAppName"]]

  PSUNotifyAppKID:
    Description: NHS Notify DoS application JWT KID secret ARN
    Value: !GetAtt PSUNotifyAppKID.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyAppKID"]]

  PSUNotifyCallbackApiKey:
    Description: PSUNotifyCallbackApiKey
    Value: !GetAtt PSUNotifyCallbackApiKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyCallbackApiKey"]]

  PSUNotifyPrivateKeySecret:
    Description: NHS Notify Private Key secret ARN
    Value: !GetAtt PSUNotifyPrivateKeySecret.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyPrivateKeySecret"]]

  PSUNotifyAppIdSecret:
    Description: NHS Notify KID (e.g. bd492cde-b67e-487b-97fd-44b7414c8e95) secret ARN
    Value: !GetAtt PSUNotifyAppIdSecret.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyAppIdSecret"]]

  GetNotifySecretsManagedPolicy:
    Description: "Access Notify Secrets Policy ARN"
    Value: !GetAtt GetNotifySecretsManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "GetNotifySecretsManagedPolicy"]]

  #endregion
