AWSTemplateFormatVersion: "2010-09-09"

Resources:
  PrescribingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPrivateKey"

  PrescribingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPublicKey"

  DispensingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPrivateKey"

  DispensingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPublicKey"

  PrescriptionsForPatientsProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenPrivateKey"

  PrescriptionsForPatientsProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for PrescriptionsForPatients proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PrescriptionsForPatients-ProxygenPublicKey"

  epsSigningCertChain:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Cert chain used for signing prescriptions. Used to validate prescriptions are valid
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-epsSigningCertChain"

  epsSigningCertChainManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !GetAtt epsSigningCertChain.Id

  ptlPrescriptionSigningPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPrivateKey"

  ptlPrescriptionSigningPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPublicKey"

  GetNotifySecretsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: []

  #endregion

Outputs:
  PrescribingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPrivateKey"]]

  PrescribingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPublicKey"]]

  DispensingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPrivateKey"]]

  DispensingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPublicKey"]]

  FhirPrescribingProxygenPrivateKey:
    Description: FhirPrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPrivateKey"]]

  FhirPrescribingProxygenPublicKey:
    Description: FhirPrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPublicKey"]]

  FhirDispensingProxygenPrivateKey:
    Description: FhirDispensingProxygenPrivateKey
    Value: !GetAtt DispensingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPrivateKey"]]

  FhirDispensingProxygenPublicKey:
    Description: FhirDispensingProxygenPublicKey
    Value: !GetAtt DispensingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPublicKey"]]

  PrescriptionsForPatientsProxygenPrivateKey:
    Description: PrescriptionsForPatientsProxygenPrivateKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPrivateKey"]]

  PrescriptionsForPatientsProxygenPublicKey:
    Description: PrescriptionsForPatientsProxygenPublicKey
    Value: !GetAtt PrescriptionsForPatientsProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescriptionsForPatientsProxygenPublicKey"]]

  epsSigningCertChain:
    Description: epsSigningCertChain
    Value: !GetAtt epsSigningCertChain.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChain"]]

  epsSigningCertChainManagedPolicy:
    Description: epsSigningCertChainManagedPolicy
    Value: !GetAtt epsSigningCertChainManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChainManagedPolicy"]]

  ptlPrescriptionSigningPublicKey:
    Description: ptlPrescriptionSigningPublicKey
    Value: !GetAtt ptlPrescriptionSigningPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPublicKey"]]

  ptlPrescriptionSigningPrivateKey:
    Description: ptlPrescriptionSigningPrivateKey
    Value: !GetAtt ptlPrescriptionSigningPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPrivateKey"]]
