AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PrescribingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPrivateKey"

  PrescribingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPublicKey"

  DispensingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPrivateKey"

  DispensingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPublicKey"
  
Outputs:
  PrescribingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPrivateKey"]]

  PrescribingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPublicKey"]]

  DispensingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPrivateKey"]]

  DispensingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPublicKey"]]

  FhirPrescribingProxygenPrivateKey:
    Description: FhirPrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPrivateKey"]]

  FhirPrescribingProxygenPublicKey:
    Description: FhirPrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPublicKey"]]

  FhirDispensingProxygenPrivateKey:
    Description: FhirDispensingProxygenPrivateKey
    Value: !GetAtt DispensingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPrivateKey"]]

  FhirDispensingProxygenPublicKey:
    Description: FhirDispensingProxygenPublicKey
    Value: !GetAtt DispensingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPublicKey"]]
