AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PrescribingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPrivateKey"

  PrescribingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPublicKey"

  DispensingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPrivateKey"

  DispensingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPublicKey"

  epsSigningCertChain:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Cert chain used for signing prescriptions. Used to validate prescriptions are valid
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-epsSigningCertChain"

  epsSigningCertChainManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !GetAtt epsSigningCertChain.Id

  ptlPrescriptionSigningPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPrivateKey"

  ptlPrescriptionSigningPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPublicKey"

  PSUNotifyCallbackAppName:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The Digital Onboarding Service application name used when calculating the signature for the notify callback
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-Application-Name"

  PSUNotifyCallbackApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The API key used when calculating the signature for the NHS notify callback
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-API-Key"

  GetNotifySecretsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref PSUNotifyCallbackAppName
              - !Ref PSUNotifyCallbackApiKey


  RegressionTestSecretsRef:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The secrets for regression tests in ref
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Regression-Test-Secrets-Ref"

  RegressionTestSecretsInternalDev:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The secrets for regression tests in internal dev
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Regression-Test-Secrets-Internal-Dev"

  RegressionTestSecretsInternalQa:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The secrets for regression tests in internal qa
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Regression-Test-Secrets-Internal-Qa"

  RegressionTestSecretsInt:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The secrets for regression tests in int
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Regression-Test-Secrets-Int"


  #endregion

Outputs:
  PrescribingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPrivateKey"]]

  PrescribingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PrescribingProxygenPublicKey"]]

  DispensingProxygenPrivateKey:
    Description: PrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPrivateKey"]]

  DispensingProxygenPublicKey:
    Description: PrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "DispensingProxygenPublicKey"]]

  FhirPrescribingProxygenPrivateKey:
    Description: FhirPrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPrivateKey"]]

  FhirPrescribingProxygenPublicKey:
    Description: FhirPrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPublicKey"]]

  FhirDispensingProxygenPrivateKey:
    Description: FhirDispensingProxygenPrivateKey
    Value: !GetAtt DispensingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPrivateKey"]]

  FhirDispensingProxygenPublicKey:
    Description: FhirDispensingProxygenPublicKey
    Value: !GetAtt DispensingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPublicKey"]]

  epsSigningCertChain:
    Description: epsSigningCertChain
    Value: !GetAtt epsSigningCertChain.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChain"]]

  epsSigningCertChainManagedPolicy:
    Description: epsSigningCertChainManagedPolicy
    Value: !GetAtt epsSigningCertChainManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChainManagedPolicy"]]

  ptlPrescriptionSigningPublicKey:
    Description: ptlPrescriptionSigningPublicKey
    Value: !GetAtt ptlPrescriptionSigningPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPublicKey"]]

  #region Notify Secrets Outputs
  PSUNotifyCallbackAppName:
    Description: PSUNotifyCallbackAppName
    Value: !GetAtt PSUNotifyCallbackAppName.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyCallbackAppName"]]

  PSUNotifyCallbackApiKey:
    Description: PSUNotifyCallbackApiKey
    Value: !GetAtt PSUNotifyCallbackApiKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyCallbackApiKey"]]

  GetNotifySecretsManagedPolicy:
    Description: "Access Notify Secrets Policy ARN"
    Value: !GetAtt GetNotifySecretsManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "GetNotifySecretsManagedPolicy"]]


  RegressionTestSecretsRef:
    Description: RegressionTestSecretsRef
    Value: !GetAtt RegressionTestSecretsRef.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "regression-test", "ref"]]

  RegressionTestSecretsInternalDev:
    Description: RegressionTestSecretsInternalDev
    Value: !GetAtt RegressionTestSecretsInternalDev.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "regression-test", "internal-dev"]]

  RegressionTestSecretsInternalQa:
    Description: RegressionTestSecretsInternalQa
    Value: !GetAtt RegressionTestSecretsInternalQa.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "regression-test", "internal-qa"]]

  RegressionTestSecretsInt:
    Description: RegressionTestSecretsInt
    Value: !GetAtt RegressionTestSecretsInt.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "regression-test", "int"]]

  #endregion
