AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PrescribingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for prescribing proxygen
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPrivateKey"

  PrescribingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for prescribing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Prescribing-ProxygenPublicKey"

  DispensingProxygenPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPrivateKey"

  DispensingProxygenPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key for dispensing proxygen
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-Dispensing-ProxygenPublicKey"

  epsSigningCertChain:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Cert chain used for signing prescriptions. Used to validate prescriptions are valid
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-epsSigningCertChain"

  epsSigningCertChainManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !GetAtt epsSigningCertChain.Id

  ptlPrescriptionSigningPrivateKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Private key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPrivateKey"

  ptlPrescriptionSigningPublicKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Public key used to sign prescriptions in PTL environments
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-ptlPrescriptionSigningPublicKey"

  PSUNotifyCallbackAppName:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The Digital Onboarding Service application name used when calculating the signature for the notify callback
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-Application-Name"

  PSUNotifyCallbackApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The API key used when calculating the signature for the NHS notify callback
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-API-Key"

  PSUNotifyPrivateKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: RSA private key (PEM) for signing JWT to NHS Notify
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-PrivateKey"

  PSUNotifyKidSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Key-ID (KID) header value for JWT to NHS Notify
      KmsKeyId: alias/SecretsKMSKeyAlias
      SecretString: ChangeMe
      Name: !Sub "${AWS::StackName}-PSU-Notify-KID"

  GetNotifySecretsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref PSUNotifyCallbackAppName
              - !Ref PSUNotifyCallbackApiKey
              - !Ref PSUNotifyPrivateKeySecret
              - !Ref PSUNotifyKidSecret

  #endregion

Outputs:
  FhirPrescribingProxygenPrivateKey:
    Description: FhirPrescribingProxygenPrivateKey
    Value: !GetAtt PrescribingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPrivateKey"]]

  FhirPrescribingProxygenPublicKey:
    Description: FhirPrescribingProxygenPublicKey
    Value: !GetAtt PrescribingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirPrescribingProxygenPublicKey"]]

  FhirDispensingProxygenPrivateKey:
    Description: FhirDispensingProxygenPrivateKey
    Value: !GetAtt DispensingProxygenPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPrivateKey"]]

  FhirDispensingProxygenPublicKey:
    Description: FhirDispensingProxygenPublicKey
    Value: !GetAtt DispensingProxygenPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FhirDispensingProxygenPublicKey"]]

  epsSigningCertChain:
    Description: epsSigningCertChain
    Value: !GetAtt epsSigningCertChain.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChain"]]

  epsSigningCertChainManagedPolicy:
    Description: epsSigningCertChainManagedPolicy
    Value: !GetAtt epsSigningCertChainManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "epsSigningCertChainManagedPolicy"]]

  ptlPrescriptionSigningPublicKey:
    Description: ptlPrescriptionSigningPublicKey
    Value: !GetAtt ptlPrescriptionSigningPublicKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPublicKey"]]

  ptlPrescriptionSigningPrivateKey:
    Description: ptlPrescriptionSigningPrivateKey
    Value: !GetAtt ptlPrescriptionSigningPrivateKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "ptlPrescriptionSigningPrivateKey"]]

  #region Notify Secrets Outputs
  PSUNotifyCallbackAppName:
    Description: PSUNotifyCallbackAppName
    Value: !GetAtt PSUNotifyCallbackAppName.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyCallbackAppName"]]

  PSUNotifyCallbackApiKey:
    Description: PSUNotifyCallbackApiKey
    Value: !GetAtt PSUNotifyCallbackApiKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyCallbackApiKey"]]

  PSUNotifyPrivateKeySecret:
    Description: NHS Notify Private Key secret ARN
    Value: !GetAtt PSUNotifyPrivateKeySecret.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyPrivateKeySecret"]]

  PSUNotifyKidSecret:
    Description: NHS Notify KID secret ARN
    Value: !GetAtt PSUNotifyKidSecret.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "PSUNotifyKidSecret"]]

  GetNotifySecretsManagedPolicy:
    Description: "Access Notify Secrets Policy ARN"
    Value: !GetAtt GetNotifySecretsManagedPolicy.PolicyArn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "GetNotifySecretsManagedPolicy"]]

  #endregion
