AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  trackerZone:
    Type: String
    Default: "tracker.national.nhs.uk"
    Description: >
      Domain name for tracker

Resources:
  Zone:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneConfig:
        Comment: "hosted zone for tracker"
      Name: !Ref trackerZone

  nsDevHostedZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Zone
      Name: !Join [".", ["dev", !Ref trackerZone, ""]]
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
        ]

  nsQAHostedZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Zone
      Name: !Join [".", ["qa", !Ref trackerZone, ""]]
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
        ]

  nsIntHostedZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Zone
      Name: !Join [".", ["int", !Ref trackerZone, ""]]
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
        ]

  nsRefHostedZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Zone
      Name: !Join [".", ["ref", !Ref trackerZone, ""]]
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
        ]

  nsProdHostedZoneRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref Zone
      Name: !Join [".", ["prod", !Ref trackerZone, ""]]
      Type: NS
      TTL: "900"
      ResourceRecords:
        [
          "ns-1239.awsdns-26.org",
          "ns-827.awsdns-39.net",
          "ns-409.awsdns-51.com",
          "ns-1922.awsdns-48.co.uk",
        ]
