name: cdk package code

on:
  workflow_call:


jobs:
  package_code:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH_NAME }}

      # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf
        uses: asdf-vm/actions/setup@1902764435ca0dd2f3388eea723a4f92a4eb8302
        with:
          asdf_branch: v0.14.1
  
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302
        with:
          asdf_branch: v0.14.1
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared

      - name: make install
        run: |
          make install

      - name: 'Tar files'
        run: |
          tar -rf artifact.tar \
            .tool-versions \
            packages \
            node_modules \
            package.json \
            package-lock.json \
            tsconfig.defaults.json \
            Makefile \
            cdk.json \
            scripts \
            cloudformation

      - uses: actions/upload-artifact@v4
        name: upload build artifact
        with:
          name: cdk_build_artifact
          path: artifact.tar
