name: Deploy Cloudformation Stack

on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      stack_name:
        required: true
        type: string
      template:
        required: true
        type: string
      capabilities:
        required: true
        type: string
      parameter_overrides:
        required: true
        type: string
      execute_changeset:
        description: If the changes should be deployed, 0 for yes, 1 for no
        required: true
        type: string
    secrets:
      cf_deploy_role:
        required: true

jobs:
  deploy_stack:
    name: Deploy CF Stack
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH_NAME }}
        fetch-depth: 0

    - shell: bash
      name: debug
      run: |
        pwd
        ls -la
      
    - name: Configure AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ secrets.cf_deploy_role }}
        role-session-name: github-actions

    - name: Deploy CF Stack to AWS
      id: deploy
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ inputs.stack_name }}
        template: ${{ inputs.template }}
        capabilities: ${{ inputs.capabilities }}
        parameter-overrides: ${{ inputs.parameter_overrides }}
        no-execute-changeset: ${{ inputs.execute_changeset }}
